import {TYPES,CENTER,createGame,update,build,harvest,unitAt,upgrade,upgradeCost,repair,sell,restoreMoon,moonCost,startWave,sunburst,save,load} from './engine.mjs';
import {render,project,tileAt} from './render.mjs';
import {drawIntro,INTRO_SECONDS} from './intro.mjs';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),intro=$('intro'),ic=intro.getContext('2d');
const images={};for(const name of [...new Set([...Object.values(TYPES).map(t=>t.portrait),'critter_04_catnap'])]){const im=new Image();im.src=`assets/critters/${name}.webp`;images[name]=im}
let game=createGame(),phase='menu',creative=false,selectedType='sun',selectedId=null,hover=null,last=0,acc=0,autosave=0,toastTimer,introStart=0,introHiddenAt=null,introStage=-1,muted=false,audioCtx=null;
const view={zoom:1,panX:0,panY:0,scale:1,ox:0,oy:0};let cw=0,ch=0,iw=0,ih=0;
const music=$('music');music.src='https://kunruiw1991.github.io/lumipop-kids-tv/videos/dh_02_golden_lyrics.mp4';music.loop=true;music.volume=.4;
function musicPlay(volume=.4){music.volume=volume;if(!muted)music.play().then(()=>{$('sound').textContent='🔊'}).catch(()=>{$('sound').textContent='🔈'})}
function tone(f=400,d=.15,type='sine'){if(muted)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),v=audioCtx.createGain(),t=audioCtx.currentTime;o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(35,f*.65),t+d);v.gain.setValueAtTime(.035,t);v.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(v).connect(audioCtx.destination);o.start(t);o.stop(t+d)}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1400)}
function resize(){const d=Math.min(window.devicePixelRatio||1,2),r=$('world').getBoundingClientRect();cw=r.width;ch=r.height;canvas.width=Math.round(cw*d);canvas.height=Math.round(ch*d);ctx.setTransform(d,0,0,d,0,0);iw=window.innerWidth;ih=window.innerHeight;intro.width=iw*d;intro.height=ih*d;ic.setTransform(d,0,0,d,0,0)}
new ResizeObserver(resize).observe($('world'));window.addEventListener('resize',resize);
const cards={};for(const [type,t]of Object.entries(TYPES)){const b=document.createElement('button');b.className='build-card';b.setAttribute('aria-label',`${t.name} ${t.icon}：木材 ${t.wood}，星能 ${t.star}`);b.setAttribute('aria-pressed',String(type===selectedType));const im=document.createElement('img');im.src=images[t.portrait].src;im.alt='';const icon=document.createElement('span');icon.className='unit-icon';icon.textContent=t.icon;const role=document.createElement('span');role.className='role';role.textContent=t.role;const cost=document.createElement('span');cost.className='cost';cost.textContent=`🪵${t.wood} ✦${t.star}`;b.append(im,icon,role,cost);b.addEventListener('click',()=>{if(phase!=='game')return;selectedType=type;selectedId=null;$('selection').hidden=true;sync();tone(520,.08)});$('buildBar').append(b);cards[type]=b}
function sync(){
 $('wood').textContent=game.creative?'∞':Math.floor(game.wood);$('star').textContent=game.creative?'∞':Math.floor(game.star);$('healthFill').style.width=`${game.core/game.maxCore*100}%`;$('wave').textContent=`${game.wave} / ${game.creative?'∞':6}`;$('countdown').textContent=game.waveActive?`🧟 ${game.enemies.length+game.remaining}`:game.cleared>=6?'🌙':game.creative?'∞':`⏳ ${Math.ceil(game.breakTime)}`;
 $('nextWave').disabled=phase!=='game'||game.waveActive||(!game.creative&&game.wave>=6);$('sun').disabled=phase!=='game'||game.sunCooldown>0;$('sunTime').textContent=game.sunCooldown>0?Math.ceil(game.sunCooldown):'';$('moonIcon').textContent=['🌑','🌒','🌓','🌕'][game.moon];$('moonPrice').textContent=game.moon===3?'✓':`✦${moonCost(game)}`;$('moon').disabled=phase!=='game'||game.moon>=3||(!game.creative&&game.star<moonCost(game));
 for(const [type,b]of Object.entries(cards)){b.classList.toggle('selected',type===selectedType);b.setAttribute('aria-pressed',String(type===selectedType));b.classList.toggle('poor',!game.creative&&(game.wood<TYPES[type].wood||game.star<TYPES[type].star))}
 const u=game.units.find(u=>u.id===selectedId);if(!u){selectedId=null;$('selection').hidden=true}else{const t=TYPES[u.type],cost=upgradeCost(u);$('selection').hidden=false;$('selectionIcon').textContent=t.icon;$('selectionLevel').textContent='★'.repeat(u.level);$('upgradePrice').textContent=u.level>=3?'✓':`🪵${cost.wood} ✦${cost.star}`;$('upgrade').disabled=u.level>=3||(!game.creative&&(game.wood<cost.wood||game.star<cost.star));$('repair').disabled=u.hp>=u.maxHp||(!game.creative&&game.wood<10)}
}
function persist(){try{if(game.over)localStorage.removeItem('moonfall-save');else localStorage.setItem('moonfall-save',save(game))}catch{}}
function menu(){phase='menu';music.pause();$('menu').hidden=false;$('pauseOverlay').hidden=true;$('cinema').hidden=true;$('pause').disabled=true;$('resultStats').hidden=true;document.querySelector('h1').textContent='MOONFALL';document.querySelector('.moon-art').textContent='🌘';document.querySelector('.menu-modes').hidden=false;document.querySelector('.menu-portraits').hidden=false;try{$('resumeSave').hidden=!load(localStorage.getItem('moonfall-save'))}catch{$('resumeSave').hidden=true}sync()}
function begin(){game=createGame({seed:(Date.now()>>>0),creative});selectedType='sun';selectedId=null;view.panX=view.panY=0;view.zoom=1;$('menu').hidden=true;$('cinema').hidden=false;phase='intro';introStart=performance.now();introStage=-1;musicPlay(.1);tone(90,.8,'triangle');resize()}
function finishIntro(){if(phase!=='intro')return;$('cinema').hidden=true;phase='game';last=performance.now();acc=0;$('pause').disabled=false;musicPlay();toast('👆 🐻 → 🧱');sync();persist()}
function pause(){if(phase==='game'){phase='paused';$('pauseOverlay').hidden=false;music.pause();persist()}else if(phase==='paused'){phase='game';$('pauseOverlay').hidden=true;last=performance.now();acc=0;musicPlay()}sync()}
function finish(){phase='result';$('menu').hidden=false;$('pause').disabled=true;$('resultStats').hidden=false;$('resultStats').textContent=`🧟 ${game.kills}　🏰 ${game.totalBuilt}　🌙 ${game.moon}/3`;document.querySelector('h1').textContent=game.over==='win'?'🌕 ✨ 🏆':'💛 🛠️';document.querySelector('.moon-art').textContent=game.over==='win'?'🌕':'🌘';document.querySelector('.menu-modes').hidden=true;document.querySelector('.menu-portraits').hidden=false;$('start').textContent='↻';$('start').setAttribute('aria-label','重新开始');$('resumeSave').hidden=true;persist();music.pause();tone(game.over==='win'?660:240,.5,'triangle')}
$('start').addEventListener('click',begin);$('skipIntro').addEventListener('click',finishIntro);$('pause').addEventListener('click',pause);$('resume').addEventListener('click',pause);$('restart').addEventListener('click',menu);
$('survival').addEventListener('click',()=>{creative=false;$('survival').classList.add('selected');$('creative').classList.remove('selected');$('survival').setAttribute('aria-pressed','true');$('creative').setAttribute('aria-pressed','false')});$('creative').addEventListener('click',()=>{creative=true;$('creative').classList.add('selected');$('survival').classList.remove('selected');$('creative').setAttribute('aria-pressed','true');$('survival').setAttribute('aria-pressed','false')});
$('resumeSave').addEventListener('click',()=>{let saved;try{saved=load(localStorage.getItem('moonfall-save'))}catch{}if(!saved)return;game=saved;creative=game.creative;phase='game';$('menu').hidden=true;$('pause').disabled=false;last=performance.now();acc=0;selectedId=null;musicPlay();sync()});
$('sound').addEventListener('click',()=>{if(!muted&&music.paused&&phase==='game'){musicPlay();return}muted=!muted;music.muted=muted;$('sound').textContent=muted?'🔇':'🔊';$('sound').setAttribute('aria-label',muted?'开启声音':'关闭声音');if(!muted&&phase==='game')musicPlay()});
$('nextWave').addEventListener('click',()=>{if(phase==='game'&&startWave(game)){toast('🧟 🧟');sync();persist()}});$('sun').addEventListener('click',()=>{if(phase==='game'&&sunburst(game)){toast('☀️');tone(160,.4,'triangle');sync()}});$('moon').addEventListener('click',()=>{if(phase==='game'&&restoreMoon(game)){toast(['','🌒','🌓','🌕'][game.moon]);tone(700,.3);sync();persist();if(game.over)finish()}});
for(const [id,fn]of [['upgrade',upgrade],['repair',repair],['sell',sell]])$(id).addEventListener('click',()=>{if(phase==='game'&&fn(game,selectedId)){sync();tone(550,.12);persist()}});
$('closeSelection').addEventListener('click',()=>{selectedId=null;sync()});$('cancelBuild').addEventListener('click',()=>{selectedType=null;selectedId=null;sync()});
$('zoomIn').addEventListener('click',()=>{view.zoom=Math.min(2.5,view.zoom*1.2)});$('zoomOut').addEventListener('click',()=>{view.zoom=Math.max(.75,view.zoom/1.2)});$('center').addEventListener('click',()=>{view.panX=view.panY=0;view.zoom=1});
const pointers=new Map();let drag=null,pinch=null;
const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
canvas.addEventListener('pointerdown',e=>{if(phase!=='game')return;canvas.setPointerCapture(e.pointerId);const p=point(e);pointers.set(e.pointerId,p);drag={...p,px:view.panX,py:view.panY,moved:false};if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:view.zoom};drag.moved=true}});
canvas.addEventListener('pointermove',e=>{const p=point(e);hover=tileAt(view,p.x,p.y);if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,p);if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()];view.zoom=Math.max(.75,Math.min(2.5,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/pinch.distance));return}if(drag){const dx=p.x-drag.x,dy=p.y-drag.y;if(Math.hypot(dx,dy)>8)drag.moved=true;if(drag.moved){view.panX=drag.px+dx;view.panY=drag.py+dy}}});
function tap(p){const tile=tileAt(view,p.x,p.y);let u=unitAt(game,tile.x,tile.y);if(!u)u=game.units.find(u=>{const q=project(view,u.x,u.y,49);return Math.hypot(p.x-q.x,p.y-q.y)<17*view.scale});if(u){selectedId=u.id;selectedType=null;sync();return}
 let tree=game.trees.find(t=>t.x===tile.x&&t.y===tile.y);if(!tree)tree=game.trees.find(t=>{const q=project(view,t.x,t.y,64);return Math.hypot(p.x-q.x,p.y-q.y)<18*view.scale});if(tree){harvest(game,tree.x,tree.y);tone(220,.07);sync();persist();return}
 if(selectedType){if(build(game,selectedType,tile.x,tile.y)){tone(500,.12);sync();persist()}else{const t=TYPES[selectedType];toast(game.wood<t.wood?'🪵 ❗':game.star<t.star?'✦ ❗':'🚫')}}else{selectedId=null;sync()}}
canvas.addEventListener('pointerup',e=>{const p=point(e);if(drag&&!drag.moved&&pointers.size===1&&phase==='game')tap(p);pointers.delete(e.pointerId);if(!pointers.size){drag=null;pinch=null}});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);drag=null;pinch=null});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(phase==='intro')finishIntro();else pause()}if(e.key===' '){e.preventDefault();if(phase==='game'&&sunburst(game))sync()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(phase==='game')pause();if(phase==='intro'){introHiddenAt=performance.now();music.pause()}}else if(phase==='intro'&&introHiddenAt!==null){introStart+=performance.now()-introHiddenAt;introHiddenAt=null;musicPlay(.1)}});window.addEventListener('blur',()=>{if(phase==='game')pause()});
function frame(now){const dt=Math.min(.12,(now-last)/1000||0);last=now;
 if(phase==='intro'){const t=(now-introStart)/1000;if(introHiddenAt===null){drawIntro(ic,iw,ih,Math.min(10,t),images);$('introProgress').firstElementChild.style.width=`${Math.min(100,t/INTRO_SECONDS*100)}%`;const stage=t<2.1?0:t<4.5?1:t<6.6?2:t<8.7?3:4;if(stage!==introStage){introStage=stage;tone([90,65,190,45,620][stage],stage===3?.7:.3,'triangle')}if(t>=INTRO_SECONDS)finishIntro()}}
 if(phase==='game'){acc+=dt;while(acc>=.1){update(game,.1);acc-=.1;if(game.over){finish();break}}autosave+=dt;if(autosave>5){autosave=0;persist()}sync()}
 if(phase!=='intro')render(ctx,cw,ch,game,view,images,selectedType,selectedId,hover,now/1000);requestAnimationFrame(frame)}
resize();menu();requestAnimationFrame(frame);
