import {GOODS,readPalace,price,buy,settle} from './palace.mjs?v=21';
import {readPieces,awardPiece,drawStoryEnding} from './story.mjs?v=21';
import {LEVELS,levelInfo,musicForLevel,makeTerrain} from './levels.mjs?v=21';
import {createGestures,configureView} from './camera.mjs?v=21';
import {TYPES,buildCost,clampHeat,heatFactor,MAX_UNIT_LEVEL,FOOTPRINTS,unitCount,buildReady,MATERIALS,afford,canRepair,repairCost,CENTER,finishCreative,nextLevel,levelNumber,createGame,update,build,harvest,unitAt,upgrade,upgradeCost,repair,sell,restoreMoon,moonCost,startWave,sunburst,save,load} from './engine.mjs?v=21';
import {render,project,tileAt} from './render.mjs?v=21';
import {drawIntro,INTRO_SECONDS} from './intro.mjs?v=21';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),intro=$('intro'),ic=intro.getContext('2d');
let unlocked=1,chosenLevel=1;try{unlocked=levelNumber(Number(localStorage.getItem('moonfall-unlocked')))}catch{}
let pieces=[];try{pieces=readPieces(localStorage.getItem('moonfall-pieces'),unlocked)}catch{}
let palace=readPalace(null);try{palace=readPalace(localStorage.getItem('moonfall-palace'))}catch{}
let shopNext=null;
function savePalace(){try{localStorage.setItem('moonfall-palace',JSON.stringify(palace))}catch{}}
let awardedPiece=0;
let celebrationStart=0,celebrationNotes=0;const partyCanvas=$('confetti'),partyCtx=partyCanvas.getContext('2d');
const images={};for(const name of [...new Set([...Object.values(TYPES).map(t=>t.portrait),'critter_04_catnap'])]){const im=new Image();im.src=`assets/critters/${name}.webp`;images[name]=im}
let selectedHeat=0;let upgradeMode=false;let game=createGame(),phase='menu',creative=false,selectedType='sun',selectedId=null,hover=null,last=0,acc=0,autosave=0,toastTimer,introStart=0,introHiddenAt=null,introStage=-1,muted=false,audioCtx=null;
const view={rotation:0,zoom:1,panX:0,panY:0,scale:1,ox:0,oy:0};let cw=0,ch=0,iw=0,ih=0;
const music=$('music');music.src=musicForLevel(1);music.loop=true;music.volume=.4;
function musicPlay(volume=.4){const src=musicForLevel(game.level);if(music.src!==src)music.src=src;music.setAttribute('aria-label',levelInfo(game.level).song);music.volume=volume;if(!muted)music.play().then(()=>{$('sound').textContent='🔊'}).catch(()=>{$('sound').textContent='🔈'})}
function tone(f=400,d=.15,type='sine'){if(muted)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),v=audioCtx.createGain(),t=audioCtx.currentTime;o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(35,f*.65),t+d);v.gain.setValueAtTime(.035,t);v.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(v).connect(audioCtx.destination);o.start(t);o.stop(t+d)}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1400)}
function resize(){const d=Math.min(window.devicePixelRatio||1,2),r=$('world').getBoundingClientRect();cw=r.width;ch=r.height;canvas.width=Math.round(cw*d);canvas.height=Math.round(ch*d);ctx.setTransform(d,0,0,d,0,0);iw=window.innerWidth;ih=window.innerHeight;intro.width=iw*d;intro.height=ih*d;ic.setTransform(d,0,0,d,0,0)}
new ResizeObserver(resize).observe($('world'));window.addEventListener('resize',resize);
const materialIcons={wood:'🪵',straw:'🌾',brick:'🧱',star:'✦',blueStar:'💎',goldStar:'🌟'};const costText=c=>MATERIALS.filter(k=>c[k]>0).map(k=>`${materialIcons[k]}${c[k]}`).join(' ');
const cards={};for(const [type,t]of ['sun','rapid','prism','spring','boost','wall','shield','heal','mill','garden','kiln'].map(type=>[type,TYPES[type]])){const b=document.createElement('button');b.className='build-card';const group=['sun','rapid','prism','spring','boost'].includes(type)?'attack':['wall','shield'].includes(type)?'defense':type==='heal'?'heal':'produce';b.dataset.group=group;b.style.setProperty('--group-color',({attack:'#dca879',defense:'#92afd9',heal:'#df9eb9',produce:'#91b790'})[group]);b.setAttribute('aria-label',`${t.name} ${t.icon}：木材 ${t.wood}，稻草 ${t.straw}，砖 ${t.brick}，星能 ${t.star}，钻石 ${t.blueStar}，金星 ${t.goldStar}`);b.setAttribute('aria-pressed',String(type===selectedType));const im=document.createElement('img');im.src=images[t.portrait].src;im.alt='';const icon=document.createElement('span');icon.className='unit-icon';icon.textContent=t.icon;const role=document.createElement('span');role.className='role';role.textContent=t.produceStraw?'🌾↗':t.produceBrick?'🔥🧱':t.heal?'💗↗':t.role;const cost=document.createElement('span');cost.className='cost';cost.innerHTML=MATERIALS.filter(k=>!['blueStar','goldStar'].includes(k)||t[k]>0).map((k,i)=>`<span class="material ${t[k]?'':'zero'}">${materialIcons[k]} <b>${t[k]||'–'}</b></span>`).join('');const count=document.createElement('span');count.className='capacity';const shape=document.createElement('span');shape.className='footprint';const cells=FOOTPRINTS[type]||[[0,0]];shape.setAttribute('aria-label',`占地 ${cells.length} 格`);shape.innerHTML=`<svg viewBox="0 0 28 28" aria-hidden="true">${cells.map(([x,y])=>`<rect x="${2+x*13}" y="${2+y*13}" width="11" height="11" rx="2"/>`).join('')}</svg>`;const meta=document.createElement('span');meta.className='card-meta';meta.append(count,shape);b.append(im,icon,role,cost,meta);b.capacity=count;b.costElement=cost;b.addEventListener('click',()=>{if(phase!=='game'||!buildReady(game,type))return;upgradeMode=false;selectedType=type;selectedId=null;$('selection').hidden=true;sync();tone(520,.08)});$('buildBar').append(b);cards[type]=b}
$('upgradeToolCost').innerHTML=MATERIALS.filter(k=>upgradeCost()[k]>0).map(k=>`<span class="material">${materialIcons[k]} <b>${upgradeCost()[k]}</b></span>`).join('');
$('upgradeTool').onclick=()=>{if(phase!=='game')return;upgradeMode=!upgradeMode;selectedType=null;selectedId=null;$('selection').hidden=true;sync();if(upgradeMode)toast('⬆️ → 🏰')};
function sync(){canvas.style.cursor=upgradeMode?'crosshair':'default';$('upgradeTool').classList.toggle('selected',upgradeMode);$('upgradeTool').setAttribute('aria-pressed',String(upgradeMode));$('upgradeTool').classList.toggle('poor',!afford(game,upgradeCost()));
 $('heatBadge').textContent=`🔥${game.heat}`;$('buildTotal').textContent=`🧱 ${game.units.length}`;$('moonProgress').textContent=`🌙 ${pieces.length}/6`;$('moonProgress').setAttribute('aria-label',`已收集 ${pieces.length} 块月亮碎片，共六块`);$('finishSession').hidden=!game.creative;$('finishSession').disabled=phase!=='game';$('levelBadge').textContent=game.creative?'🧱 ∞':`${levelInfo(game.level).icon} ${game.level}`;$('wood').textContent=game.creative?'∞':Math.floor(game.wood);$('star').textContent=game.creative?'∞':Math.floor(game.star);for(const k of ['blueStar','goldStar'])$(k).textContent=game.creative?'∞':Math.floor(game[k]||0);$('straw').textContent=game.creative?'∞':Math.floor(game.straw);$('brick').textContent=game.creative?'∞':Math.floor(game.brick);$('healthFill').style.width=`${game.core/game.maxCore*100}%`;$('wave').textContent=`${game.wave} / ${game.creative?'∞':6}`;$('countdown').textContent=game.waveActive?`🧟 ${game.enemies.length+game.remaining}`:game.cleared>=6?'🌙':game.creative?'∞':`⏳ ${Math.ceil(game.breakTime)}`;
 $('nextWave').disabled=phase!=='game'||game.waveActive||(!game.creative&&game.wave>=6);$('sun').disabled=phase!=='game'||game.sunCooldown>0;$('sunTime').textContent=game.sunCooldown>0?Math.ceil(game.sunCooldown):'';$('moonIcon').textContent='🛡️';$('moonPrice').textContent=game.moon===3?'✓':`✦${moonCost(game)}`;$('moon').disabled=phase!=='game'||game.moon>=3||(!game.creative&&game.star<moonCost(game));
 for(const [type,b]of Object.entries(cards)){b.classList.toggle('selected',type===selectedType);b.setAttribute('aria-pressed',String(type===selectedType));const ready=buildReady(game,type);b.classList.toggle('poor',!ready);b.disabled=!ready;b.capacity.textContent=`×${unitCount(game,type)}`;const cost=buildCost(game,type),stamp=JSON.stringify(cost);if(b.costStamp!==stamp){b.costStamp=stamp;b.costElement.innerHTML=MATERIALS.filter(k=>!['blueStar','goldStar'].includes(k)||cost[k]>0).map(k=>`<span class="material ${cost[k]?'':'zero'}">${materialIcons[k]} <b>${cost[k]||'–'}</b></span>`).join('');b.setAttribute('aria-label',`${TYPES[type].name} ${costText(cost)}`)}}
 const u=game.units.find(u=>u.id===selectedId);if(!u){selectedId=null;$('selection').hidden=true}else{const t=TYPES[u.type],cost=upgradeCost(u);$('selection').hidden=false;$('selectionIcon').textContent=t.icon;$('selectionLevel').textContent='★'.repeat(u.level);$('repair').disabled=!canRepair(game,u)}
}
function persist(){try{if(game.over)localStorage.removeItem('moonfall-save');else localStorage.setItem('moonfall-save',save(game))}catch{}}
function levelPicker(){const limit=creative?Math.max(LEVELS.length,unlocked):unlocked;chosenLevel=Math.max(1,Math.min(limit,chosenLevel));const info=levelInfo(chosenLevel);$('levelChoice').textContent=`${info.icon} ${chosenLevel}`;$('levelDown').disabled=chosenLevel<=1;$('levelUp').disabled=chosenLevel>=limit;$('levelPicker').hidden=false;$('levelChoice').setAttribute('aria-label',info.name);$('mapPreview').setAttribute('aria-label',info.name);const c=$('mapPreview').getContext('2d'),cells=makeTerrain(chosenLevel);c.clearRect(0,0,220,108);for(let y=0;y<18;y++)for(let x=0;x<22;x++){const t=cells[y*22+x];c.fillStyle=({water:'#427ea1',rock:'#454050',lava:'#ee8253',bridge:'#e1c390',ice:'#61ddeb',burrow:'#963b81',sand:'#dba764'})[t]||info.ground[0];c.fillRect(x*10,y*6,9,5)}c.fillStyle='#ffe3a1';c.fillRect(105,49,12,12)}
$('levelDown').onclick=()=>{chosenLevel--;levelPicker()};$('levelUp').onclick=()=>{chosenLevel++;levelPicker()};
function syncHeat(){selectedHeat=clampHeat(selectedHeat);$('heat').value=selectedHeat;$('heatValue').textContent=selectedHeat;$('heatScale').textContent=`🧱 ×${(1+selectedHeat*.2).toFixed(1)}　🧟 💚⚔️ ×${(1+selectedHeat*.2).toFixed(1)}`;$('heat').setAttribute('aria-valuetext',`Heat ${selectedHeat} / 10`)}
$('heat').addEventListener('input',()=>{selectedHeat=clampHeat($('heat').value);syncHeat()});
function menu(){syncHeat();phase='menu';$('ending').hidden=true;levelPicker();music.pause();$('menu').hidden=false;$('pauseOverlay').hidden=true;$('cinema').hidden=true;$('pause').disabled=true;$('resultStats').hidden=true;document.querySelector('h1').textContent='MOONFALL';document.querySelector('.moon-art').textContent='🌘';document.querySelector('.menu-modes').hidden=false;document.querySelector('.menu-portraits').hidden=false;let saved;try{saved=load(localStorage.getItem('moonfall-save'))}catch{}const available=!!saved&&!saved.over;$('resumeSave').disabled=!available;$('savePreview').textContent=available?`${levelInfo(saved.level).icon} ${saved.level} · 🧟 ${saved.wave}/6 · 🔥${saved.heat}`:'暂无存档 · No save';$('resumeSave').setAttribute('aria-label',available?`读取存档 Load Game，Level ${saved.level}，Wave ${saved.wave}`:'读取存档 Load Game，暂无存档 No save');sync()}
function begin(skip=false){upgradeMode=false;game=createGame({seed:(Date.now()>>>0),creative,level:chosenLevel,upgrades:palace.upgrades,heat:selectedHeat});$('ending').hidden=true;selectedType='sun';selectedId=null;view.panX=view.panY=0;view.zoom=1;view.rotation=0;$('menu').hidden=true;$('cinema').hidden=false;phase='intro';introStart=performance.now();introStage=-1;musicPlay(.1);tone(90,.8,'triangle');resize();if(skip===true||chosenLevel>1)finishIntro()}
function finishIntro(){if(phase!=='intro')return;$('cinema').hidden=true;phase='game';last=performance.now();acc=0;$('pause').disabled=false;musicPlay();toast('👆 🐻 → 🧱');sync();persist()}
function pause(){gestures.reset();if(phase==='game'){phase='paused';$('pauseOverlay').hidden=false;music.pause();persist()}else if(phase==='paused'){phase='game';$('pauseOverlay').hidden=true;last=performance.now();acc=0;musicPlay()}sync()}
function finish(){if(phase==='result')return;phase='result';const won=game.over==='win';$('menu').hidden=true;$('pauseOverlay').hidden=true;$('ending').hidden=false;$('ending').classList.toggle('defeat',!won);$('pause').disabled=true;selectedId=null;$('selection').hidden=true;
 const before=pieces;pieces=awardPiece(pieces,game);awardedPiece=pieces.length>before.length?game.level:0;try{localStorage.setItem('moonfall-pieces',JSON.stringify(pieces))}catch{}
 const complete=won&&!game.creative&&pieces.length===6;$('ending').classList.toggle('complete',complete);$('storyScene').hidden=!won||game.creative;$('endingMoon').hidden=won&&!game.creative;$('party').hidden=complete;$('endingTrophy').hidden=complete;
 const result=settle(palace,game);savePalace();$('scorePanel').hidden=game.creative;$('scorePanel').textContent=`🏰 ${result.buildings} + 📦 ${result.resources} + 💚 ${result.health} + 🏁 ${result.clear} + ⚡ ${result.pace} + 🗺️ ${result.challenge} = ⭐ ${result.total}　🌙 +${result.earned}`;
 $('endingMoon').textContent=won?'🌟':'🌘';$('endingTrophy').textContent=won?'🏆':'💛 🛠️';$('endingStats').textContent=game.creative?'🧱 ✨':`🌙 ${pieces.length}/6　${awardedPiece?'🧩 +1':''}`;
 const next=nextLevel(game);$('harder').hidden=!next;if(next){unlocked=Math.max(unlocked,next);try{localStorage.setItem('moonfall-unlocked',String(unlocked))}catch{}$('harder').textContent=`🔥 ${next} ➜`;musicPlay(.25)}else music.pause();
 $('party').replaceChildren();Object.values(TYPES).slice(0,8).forEach((t,i)=>{const im=document.createElement('img');im.src=images[t.portrait].src;im.alt=t.name;im.style.setProperty('--i',i);$('party').append(im)});celebrationStart=performance.now();celebrationNotes=0;persist();sync();(next?$('harder'):$('retry')).focus();if(!won)tone(240,.4,'triangle')}
$('harder').onclick=()=>{const next=nextLevel(game);if(!next)return;openShop(next)};
function syncShop(){
 $('moonWallet').textContent=`🌙 ${palace.moons}`;
 for(const [k,b] of Object.entries(shopCards)){const n=palace.upgrades[k];b.disabled=n>=3||palace.moons<price(palace,k);b.textContent=`${GOODS[k].icon} ${'★'.repeat(n)}${'☆'.repeat(3-n)}\n${GOODS[k].effect}\n${n>=3?'✓':`🌙 ${price(palace,k)}`}`}
}
const shopCards={};for(const [k,item]of Object.entries(GOODS)){const b=document.createElement('button');b.setAttribute('aria-label',`${item.label}，本轮强化，下关生效`);b.onclick=()=>{if(buy(palace,k)){savePalace();syncShop();tone(700,.15)}};$('shopItems').append(b);shopCards[k]=b}
function openShop(next=null){shopNext=next;$('palace').hidden=false;$('shopGo').hidden=!next;syncShop()}
$('openPalace').onclick=()=>openShop();$('menuPalace').onclick=()=>openShop();
$('shopClose').onclick=()=>{$('palace').hidden=true};
$('shopGo').onclick=()=>{if(!shopNext)return;chosenLevel=shopNext;creative=false;$('palace').hidden=true;begin(true)};
$('retry').onclick=()=>{chosenLevel=game.level;creative=game.creative;begin(true)};
$('finishSession').onclick=()=>{if(phase==='game'&&finishCreative(game))finish()};
$('endingHome').onclick=()=>{chosenLevel=game.level;menu()};
function celebration(now){const seconds=(now-celebrationStart)/1000;if(game.over==='win'&&!game.creative){const scene=$('storyScene');drawStoryEnding(scene.getContext('2d'),640,300,matchMedia('(prefers-reduced-motion: reduce)').matches?10:seconds,pieces,images,Object.values(TYPES),awardedPiece)}if(game.over==='win'&&celebrationNotes<7&&seconds>=celebrationNotes*.18){tone([523,659,784,1047,784,880,1047][celebrationNotes++],.25,'triangle')}
 const d=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;if(partyCanvas.width!==Math.round(w*d)||partyCanvas.height!==Math.round(h*d)){partyCanvas.width=Math.round(w*d);partyCanvas.height=Math.round(h*d)}partyCtx.setTransform(d,0,0,d,0,0);partyCtx.clearRect(0,0,w,h);if(game.over!=='win'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const colors=['#ffe49b','#b8edc0','#f7b4d4','#a8dfff','#d2b7ff'];for(let i=0;i<110;i++){const t=seconds*(30+i%37),x=((i*137.5)%w)+Math.sin(seconds+i)*22,y=(i*79+t)%(h+40)-20;partyCtx.save();partyCtx.translate(x,y);partyCtx.rotate(seconds*(i%2?1:-1)+i);partyCtx.fillStyle=colors[i%5];partyCtx.fillRect(-4,-7,8,14);partyCtx.restore()}
 for(let j=0;j<4;j++){const t=(seconds+j*.61)%2.6,r=t*75,alpha=Math.max(0,1-t/2.6);partyCtx.globalAlpha=alpha;partyCtx.fillStyle=colors[j];const x=w*(.15+j*.23),y=h*(.22+(j%2)*.16);for(let i=0;i<16;i++){const a=i*Math.PI/8;partyCtx.beginPath();partyCtx.arc(x+Math.cos(a)*r,y+Math.sin(a)*r,3,0,Math.PI*2);partyCtx.fill()}}partyCtx.globalAlpha=1;
}
function newGame(){
 // A new campaign must not inherit reward records or fragments from a previous run.
 pieces=[];awardedPiece=0;palace=readPalace(null);shopNext=null;
 if(!creative){chosenLevel=1;unlocked=1}
 $('palace').hidden=true;savePalace();syncShop();
 try{localStorage.setItem('moonfall-pieces','[]');localStorage.setItem('moonfall-unlocked',String(unlocked));localStorage.removeItem('moonfall-save')}catch{}
 begin();sync();persist();
}
$('start').addEventListener('click',newGame);$('skipIntro').addEventListener('click',finishIntro);$('pause').addEventListener('click',pause);$('resume').addEventListener('click',pause);$('restart').addEventListener('click',menu);
$('survival').addEventListener('click',()=>{creative=false;levelPicker();$('survival').classList.add('selected');$('creative').classList.remove('selected');$('survival').setAttribute('aria-pressed','true');$('creative').setAttribute('aria-pressed','false')});$('creative').addEventListener('click',()=>{creative=true;levelPicker();$('creative').classList.add('selected');$('survival').classList.remove('selected');$('creative').setAttribute('aria-pressed','true');$('survival').setAttribute('aria-pressed','false')});
$('resumeSave').addEventListener('click',()=>{let saved;try{saved=load(localStorage.getItem('moonfall-save'))}catch{}if(!saved||saved.over)return;upgradeMode=false;game=saved;creative=game.creative;chosenLevel=game.level;selectedHeat=game.heat;syncHeat();selectedType=null;hover=null;view.panX=view.panY=view.rotation=0;view.zoom=1;gestures.reset();$('selection').hidden=true;phase='game';$('menu').hidden=true;$('pause').disabled=false;last=performance.now();acc=0;selectedId=null;musicPlay();sync();update(game,0);if(game.over)finish()});
$('sound').addEventListener('click',()=>{if(!muted&&music.paused&&phase==='game'){musicPlay();return}muted=!muted;music.muted=muted;$('sound').textContent=muted?'🔇':'🔊';$('sound').setAttribute('aria-label',muted?'开启声音':'关闭声音');if(!muted&&phase==='game')musicPlay()});
$('nextWave').addEventListener('click',()=>{if(phase==='game'&&startWave(game)){toast('🧟 🧟');sync();persist()}});$('sun').addEventListener('click',()=>{if(phase==='game'&&sunburst(game)){toast('☀️');tone(160,.4,'triangle');sync()}});$('moon').addEventListener('click',()=>{if(phase==='game'&&restoreMoon(game)){toast('🛡️ 💚');tone(700,.3);sync();persist();if(game.over)finish()}});
for(const [id,fn]of [['repair',repair],['sell',sell]])$(id).addEventListener('click',()=>{if(phase==='game'&&fn(game,selectedId)){sync();tone(550,.12);persist()}});
$('closeSelection').addEventListener('click',()=>{selectedId=null;sync()});$('cancelBuild').addEventListener('click',()=>{upgradeMode=false;selectedType=null;selectedId=null;sync()});
$('zoomIn').addEventListener('click',()=>{view.zoom=Math.min(2.5,view.zoom*1.2)});$('zoomOut').addEventListener('click',()=>{view.zoom=Math.max(.75,view.zoom/1.2)});$('center').addEventListener('click',()=>{view.panX=view.panY=0;view.zoom=1;view.rotation=0});
const gestures=createGestures(view,()=>configureView(view,cw,ch),p=>{if(phase==='game')tap(p)});
const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
canvas.addEventListener('pointerdown',e=>{if(phase!=='game')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);gestures.down(e.pointerId,point(e))});
canvas.addEventListener('pointermove',e=>{const p=point(e);gestures.move(e.pointerId,p);hover=tileAt(view,p.x,p.y)});
function tap(p){const tile=tileAt(view,p.x,p.y);let u=unitAt(game,tile.x,tile.y);if(!u)u=[...game.units].sort((a,b)=>project(view,b.x,b.y).y-project(view,a.x,a.y).y).find(u=>{const q=project(view,u.x,u.y,49);return Math.hypot(p.x-q.x,p.y-q.y)<17*view.scale});if(upgradeMode){if(u){if(upgrade(game,u.id)){tone(740,.15);persist();toast('⬆️ '+u.level)}else toast(u.level>=MAX_UNIT_LEVEL?'✓ MAX':'📦 ❗')}else toast('⬆️ → 🏰');sync();return}if(u){selectedId=u.id;selectedType=null;sync();return}
 let tree=game.trees.find(t=>t.x===tile.x&&t.y===tile.y);if(!tree)tree=[...game.trees].sort((a,b)=>project(view,b.x,b.y).y-project(view,a.x,a.y).y).find(t=>{const q=project(view,t.x,t.y,64);return Math.hypot(p.x-q.x,p.y-q.y)<18*view.scale});if(tree){harvest(game,tree.x,tree.y);tone(220,.07);sync();persist();return}
 if(selectedType){if(build(game,selectedType,tile.x,tile.y)){tone(500,.12);sync();persist()}else{const t=buildCost(game,selectedType),missing=MATERIALS.find(k=>(game[k]||0)<(t[k]||0));toast(missing?`${materialIcons[missing]} ❗`:'🚫')}}else{selectedId=null;sync()}}
canvas.addEventListener('pointerup',e=>gestures.up(e.pointerId,point(e)));canvas.addEventListener('pointercancel',e=>gestures.up(e.pointerId,point(e),true));canvas.addEventListener('lostpointercapture',e=>gestures.up(e.pointerId,point(e),true));
canvas.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});canvas.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});
for(const [id,delta]of [['rotateLeft',-Math.PI/4],['rotateRight',Math.PI/4]])$(id).onclick=()=>{gestures.reset();view.rotation+=delta;configureView(view,cw,ch)};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(phase==='intro')finishIntro();else pause()}if(e.key===' '){e.preventDefault();if(phase==='game'&&sunburst(game))sync()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(phase==='game')pause();if(phase==='intro'){introHiddenAt=performance.now();music.pause()}}else if(phase==='intro'&&introHiddenAt!==null){introStart+=performance.now()-introHiddenAt;introHiddenAt=null;musicPlay(.1)}});window.addEventListener('blur',()=>{if(phase==='game')pause()});
function frame(now){const dt=Math.min(.5,(now-last)/1000||0);last=now;
 if(phase==='intro'){const t=(now-introStart)/1000;if(introHiddenAt===null){drawIntro(ic,iw,ih,Math.min(10,t),images);$('introProgress').firstElementChild.style.width=`${Math.min(100,t/INTRO_SECONDS*100)}%`;const stage=t<2.1?0:t<4.5?1:t<6.6?2:t<8.7?3:4;if(stage!==introStage){introStage=stage;tone([90,65,190,45,620][stage],stage===3?.7:.3,'triangle')}if(t>=INTRO_SECONDS)finishIntro()}}
 if(phase==='game'){acc+=dt;while(acc>=.1){update(game,.1);acc-=.1;if(game.over){finish();break}}autosave+=dt;if(autosave>5){autosave=0;persist()}sync()}
 if(phase==='result')celebration(now);
 if(phase!=='intro')render(ctx,cw,ch,game,view,images,selectedType,selectedId,hover,now/1000,upgradeMode);requestAnimationFrame(frame)}
resize();menu();requestAnimationFrame(frame);
