import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,build,TYPES,update,repair,upgrade,load,save,clearShot,ENEMIES} from '../engine.mjs';
const calm=()=>{const g=createGame();g.wave=6;g.units=[];g.trees=[];return g};
test('brick and straw costs are real and rejected purchases never spend partial resources',()=>{const g=calm();g.brick=0;const w=g.wood;assert.equal(build(g,'wall',10,9),false);assert.equal(g.wood,w);g.brick=16;assert.ok(build(g,'wall',10,9));assert.equal(g.brick,0);g.straw=0;assert.equal(build(g,'rapid',12,9),false)});
test('pig produces straw and kiln converts wood plus straw into brick',()=>{const g=calm();build(g,'garden',10,9);const straw=g.straw;update(g,.25);assert.ok(Math.abs(g.straw-straw-.2)<1e-8);build(g,'kiln',12,9);const before={wood:g.wood,straw:g.straw,brick:g.brick};update(g,.25);assert.ok(g.brick>before.brick);assert.ok(Math.abs(g.wood-before.wood-(.22-.45*.35)*.25)<1e-8);assert.ok(Math.abs(g.straw-before.straw-(.8-.45*.7)*.25)<1e-8);g.straw=0;g.units=g.units.filter(u=>u.type==='kiln');const brick=g.brick;update(g,.25);assert.equal(g.brick,brick);assert.equal(g.units[0].producing,false)});
test('bears have one shared repair budget per target, consume straw and cannot heal the core',()=>{const g=calm();g.wood=g.star=g.straw=g.brick=999;const a=build(g,'wall',10,9);build(g,'heal',10,10);build(g,'heal',9,9);a.hp-=100;g.core=400;const hp=a.hp,straw=g.straw;update(g,.25);assert.equal(a.hp,hp+.25);assert.equal(g.core,400);assert.ok(g.straw<straw);a.lastHit=g.time;const hurt=a.hp;update(g,.25);assert.equal(a.hp,hurt);g.time+=4;g.straw=0;update(g,.25);assert.equal(a.hp,hurt)});
test('manual repair is small, costs three materials and has a cooldown',()=>{const g=calm();g.wood=g.straw=g.brick=999;const u=build(g,'wall',10,9);u.hp=20;const before=u.hp;assert.ok(repair(g,u.id));assert.equal(u.hp,before+u.maxHp*.15);assert.equal(repair(g,u.id),false);g.time+=8;u.lastHit=g.time;assert.equal(repair(g,u.id),false)});
test('upgrade does not erase damage and old saves receive material migration',()=>{const g=calm();g.wood=g.star=g.straw=g.brick=999;const u=build(g,'sun',10,9);u.hp-=100;upgrade(g,u.id);assert.equal(u.maxHp-u.hp,100);delete g.straw;delete g.brick;const old=load(save(g));assert.equal(old.straw,50);assert.equal(old.brick,35)});
test('rock blocks direct turret fire and enemy silhouettes differ in size and palette',()=>{const g=calm();g.terrain[9*22+8]='rock';assert.equal(clearShot(g,{x:7,y:9},{x:9,y:9}),false);assert.equal(clearShot(g,{x:7,y:8},{x:9,y:8}),true);assert.ok(ENEMIES.brute.size>ENEMIES.runner.size*2);assert.notEqual(ENEMIES.runner.color,ENEMIES.zombie.color);assert.equal(TYPES.heal.heal,1)});
