import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,makeEnemy,update,build,finishCreative,nextLevel,enemyKind} from '../engine.mjs';
function arena(){const g=createGame();g.wave=6;g.waveActive=true;g.remaining=0;g.units=[];g.trees=[];return g}
test('last enemy death triggers the ending on the same tick without moon purchases',()=>{const g=arena();g.star=0;g.moon=0;const e=makeEnemy(g,'boss',2,2);e.hp=0;g.enemies=[e];update(g,.1);assert.equal(g.over,'win');assert.equal(g.moon,3);assert.equal(g.kills,1);assert.equal(nextLevel(g),2)});
test('base destruction beats final-wave completion',()=>{const g=arena();g.core=1;const e=makeEnemy(g,'bomber',11,9);e.fuse=.01;g.enemies=[e];update(g,.1);assert.equal(g.over,'lose');assert.equal(nextLevel(g),null)});
test('ranged spitter damages a building from three cells away',()=>{const g=arena();g.wood=999;const wall=build(g,'wall',8,9),e=makeEnemy(g,'spitter',5,9);g.enemies=[e];update(g,.1);assert.equal(wall.hp,wall.maxHp-e.damage);assert.ok(g.effects.some(f=>f.kind==='spit'))});
test('bomber warns before exploding, damages walls and disappears',()=>{const g=arena();g.wood=999;const wall=build(g,'wall',7,9),e=makeEnemy(g,'bomber',6,9);g.enemies=[e];update(g,.1);assert.equal(wall.hp,wall.maxHp);assert.ok(e.fuse>0);for(let i=0;i<16;i++)update(g,.1);assert.ok(wall.hp<wall.maxHp);assert.equal(g.enemies.length,0)});
test('healer heals allies only and overlapping healing does not stack',()=>{const g=arena(),a=makeEnemy(g,'zombie',2,2),h=makeEnemy(g,'healer',2,3),h2=makeEnemy(g,'healer',3,2);a.hp-=10;h.hp-=10;g.enemies=[a,h,h2];const hp=a.hp;update(g,.1);assert.ok(Math.abs(a.hp-hp-.3)<1e-8);g.enemies=[h];const before=h.hp;update(g,.1);assert.equal(h.hp,before)});
test('summoner creates only two finite minions and completion waits for them',()=>{const g=arena(),e=makeEnemy(g,'summoner',1,1);e.speed=0;g.enemies=[e];for(let i=0;i<3;i++){e.summonClock=0;update(g,.1)}assert.equal(e.summons,2);assert.equal(g.enemies.filter(e=>e.kind==='mini').length,2);e.hp=0;update(g,.1);assert.equal(g.over,null);g.enemies.forEach(e=>e.hp=0);update(g,.1);assert.equal(g.over,'win')});
test('waves introduce all special roles and always finish wave six with CatNap',()=>{const kinds=new Set();for(let w=1;w<=6;w++)for(let n=1;n<=5+w*3;n++)kinds.add(enemyKind(w,n));for(const kind of ['runner','brute','spitter','bomber','healer','summoner'])assert.ok(kinds.has(kind));assert.equal(enemyKind(6,1),'boss')});
test('creative mode has a deliberate celebratory finish without unlocking survival',()=>{const g=createGame({creative:true});assert.ok(finishCreative(g));assert.equal(g.over,'win');assert.equal(nextLevel(g),null);assert.equal(finishCreative(g),false)});
test('spitter prioritizes production and punishes adjacent structures rather than isolated walls',()=>{const g=arena();g.wood=g.straw=g.brick=g.star=999;const outer=build(g,'wall',8,9),kiln=build(g,'kiln',10,9),neighbor=build(g,'wall',10,10),e=makeEnemy(g,'spitter',5,9);g.enemies=[e];update(g,.1);assert.equal(outer.hp,outer.maxHp);assert.equal(kiln.hp,kiln.maxHp-e.damage);assert.equal(neighbor.hp,neighbor.maxHp-e.damage*.7)});
